import React from 'react'
import Head from "next/head";
const PageMataTag = () => {
  return (
    <>
     <Head>
          <title>Impulse Proxies</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="title" content="Elevate your success with our Proxies" />
          <meta
            name="description"
            content="Elevate your success with our Proxies"
          />
          {/* <!-- Open Graph / Facebook --> */}
          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://metatags.io/" />
          <meta
            property="og:title"
            content="Elevate your success with our Proxies"
          />
          <meta
            property="og:description"
            content="Elevate your success with our Proxies"
          />
          <meta
            property="og:image"
            content="https://impulse-proxies-01.vercel.app/MetaTag.png"
          />
          {/* <!-- Twitter --> */}
          <meta
            property="twitter:card"
            content="Elevate your success with our Proxies"
          />
          <meta property="twitter:url" content="https://metatags.io/" />
          <meta
            property="twitter:title"
            content="Elevate your success with our Proxies"
          />
          <meta
            property="twitter:description"
            content="Elevate your success with our Proxies"
          />
          <meta
            property="twitter:image"
            content="https://impulse-proxies-01.vercel.app/MetaTag.png"
          />
        </Head>
    </>
  )
}

export default PageMataTag
